In [1]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=5)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(2, 3, 4))  # Three-dimensional array

In [2]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (2, 3, 4)
x3 size:  24


In [3]:
print("dtype:", x3.dtype)

dtype: int32


In [4]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 4 bytes
nbytes: 96 bytes


In [12]:
#Visualizzare i parametri ndim, shape e size anche degli array x1 e x2
print("PARAMETRI ARRAY UNIDIMENSIONALE")
print("x1 ndim:", x1.ndim)
print("x1 shape:",x1.shape)
print("x1 size:", x1.size)
print("PARAMETRI ARRAY BIDIMNSIONALI")
print("x2 ndim: ", x2.ndim)
print("x2 shape: ", x2.shape)
print("x2 size: ", x2.size)

PARAMETRI ARRAY UNIDIMENSIONALE
x1 ndim: 1
x1 shape: (5,)
x1 size: 5
PARAMETRI ARRAY BIDIMNSIONALI
x2 ndim:  2
x2 shape:  (3, 4)
x2 size:  12


In [14]:
#Modificare x1 in modo che ndim sia uguale a
#2 e shape sia uguale a (4, 5)
print("PARAMETRI ARRAY UNIDIMENSIONALE MODIFICATI")
#devo modificare la parte iniziale di X=1
x1 = np.random.randint(2, size= (4,5))  # One-dimensional array
print("x1 ndim:", x1.ndim)
print("x1 shape:",x1.shape)
print("x1 size:", x1.size)

PARAMETRI ARRAY UNIDIMENSIONALE MODIFICATI
x1 ndim: 2
x1 shape: (4, 5)
x1 size: 20


# Cosa indica il primo parametro di random.randint posto al valore 10?
#### il parametro random.randint va a scegliere un numero casuale tra 0 e 10 (escluso)

In [24]:
#Cambiare il primo parametro e visualizzare i nuovi valori dell’array
print("x2 MODIFICATO")
x2 = np.random.randint(80, size=(3, 4))
print(x2)

x2 MODIFICATO
[[35 64 69  0]
 [50 36 34 48]
 [ 3 42 77 21]]


In [29]:
#Cambiare il primo parametro e visualizzare i nuovi valori dell’array
print("x1 modificato")
x1 = np.random.randint(80, size=6)
print(x1)

x1 modificato
[41 58 65 36 10 43]
