In [3]:
import numpy as np
np.random.seed(0)

In [62]:
#Creare un array es1 di valori casuali interi (randint) 
#di dimensione 3x5,con valore massimo (incluso) uguale a 8. 
#Visualizzare es1
es1=np.random.randint(9,size=(3,5))
print("ARRAY INIZIALE: \n", es1)

ARRAY INIZIALE: 
 [[6 5 8 2 3]
 [7 5 3 4 5]
 [3 3 7 7 3]]


In [64]:
#Selezionare gli elementi che hanno valore 5 (5 è un esempio, 
#ovviamente potete scegliere un valore diverso), prima utilizzando 
#la posizione come indice, poi usando la forma negativa dalla 
#fine dell’array (vedere esempi)
print("POSIZIONE DEL PRIMO CINQUE")
print("posizione come indice:", es1[0,1])
print("posizione con forma negativa:", es1[0,-4])

POSIZIONE DEL PRIMO CINQUE
posizione come indice: 5
posizione con forma negativa: 5


In [66]:
print("POSIZIONE DEL SECONDO CINQUE")
print("posizione come indice:", es1[1,1])
print("posizione con forma negativa:", es1[1,-4])

POSIZIONE DEL SECONDO CINQUE
posizione come indice: 5
posizione con forma negativa: 5


In [67]:
#Selezionare il primo elemento della seconda riga, 
#il quinto elemento della prima riga, 
#il secondo elemento della seconda colonna, 
#il quarto elemento della terza colonna
print("SELEZIONARE I SEGUENTI ELEMENTI")
print("primo elemento della seconda riga:", es1[1,0])
print("il quinto elemento della prima riga:", es1[0,4])
print("il secondo elemento della seconda colonna:", es1[1,1])
print("il terzo elemento della terza colonna:", es1[2,2])

SELEZIONARE I SEGUENTI ELEMENTI
primo elemento della seconda riga: 7
il quinto elemento della prima riga: 3
il secondo elemento della seconda colonna: 5
il terzo elemento della terza colonna: 7


In [68]:
#Sommare 10 all’elemento es1[0,0],
#sottrarre 5 all’elemento es1[3,2],
#sommare l’elemento es1[0,0] all’elemento es1[1,0] 
#e il risultato metterlo in es1[2,0] 
#(non usare i valori, usare i riferimenti alle posizioni dell’array)
es1[0,0]= es1[0,0]+10
es1[2,2]= es1[2,2]-5
es1[2,0]= es1[0,0]+es1[1,0]
print("MATRICE MODIFICATA: \n",es1)

MATRICE MODIFICATA: 
 [[16  5  8  2  3]
 [ 7  5  3  4  5]
 [23  3  2  7  3]]
