In [4]:
import numpy as np

In [5]:
es3=np.random.randint(21, size=(3,3))
np.random.seed(0)
es3

array([[ 2,  0,  7],
       [14, 10,  8],
       [ 3, 10, 12]])

### COME VISTA e COME COPIA

In [6]:
#punto 1
print("array iniziale:\n", es3)

array iniziale:
 [[ 2  0  7]
 [14 10  8]
 [ 3 10 12]]


In [8]:
#punto 2 estrarre il subarray formato dalla seconda riga (es3-sub)
#come vista e visualizzarlo
es3_sub=es3[1,:]
print("il subarray estratto è il seguente:\n", es3_sub)

il subarray estratto è il seguente:
 [14 10  8]


In [11]:
#punto 3
#moltiplicare per 3 tutti gli elementi della seconda colonna di es3
es3[:,1]=es3[:,1]*3
print("seconda colonna di es3 dopo la moltiplicazione:\n", es3[:,1])

seconda colonna di es3 dopo la moltiplicazione:
 [  0 270 270]


In [14]:
#punto 4 vedo se nel subarray estratto (es3_sub) è cambiato qualcosa
#a seguito della modifica della matrice originale es3
print("visualizzo es3_sub:\n", es3_sub)
#possiamo notare che il secondo valore è cambiato, questo a dimostrazione
#che con view, una volta estratto un subarray, esso verrà influenzato da 
#tutte le eventuali modifiche fatte all'array iniziale

visualizzo es3_sub:
 [ 14 270   8]


In [17]:
print("array di partenza:\n", es3)

array di partenza:
 [[  2   0   7]
 [ 14 270   8]
 [  3 270  12]]


In [24]:
#punto 5
#estrarre il subarray formato dalla terza colonna di es3 come copia 
#(es3_sub_copy)
es3_sub_copy=es3[:,2].copy()
print("subarray come copia:\n", es3_sub_copy)

subarray come copia:
 [ 7  8 12]


In [21]:
#punto 6
#sommare 10 a tutti gli elementi di es3-sub-copy e visualizzare
es3_sub_copy= es3_sub_copy+10
print("modifiche all'array es3_sub_copy:\n", es3_sub_copy)

modifiche all'array es3_sub_copy:
 [17 18 22]


In [25]:
#punto 7
#visualizzo es3 per vedere se contiene la modifica
es3
#non c'è la modifica, in quanto i valori della terza colonna sono 
#rimasti 7,8,12 e NON quelli modificati; questo dimostra che è stata 
#modificata solo la copia e non l'array iniziale

array([[  2,   0,   7],
       [ 14, 270,   8],
       [  3, 270,  12]])