In [1]:
import numpy as np

### ESERCIZIO RESHAPE, CONCATENATE E SPLITTING

In [6]:
#punto 1 
#Creare una lista es4 di 36 valori interi crescenti 
#partendo da 1
es4=np.arange(1,37)
es4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36])

In [20]:
#punto 2 
#Trasformarlo in un array di dimensione 6x6
es4=es4.reshape(6,6)
print("array di partenza:\n",es4)

array di partenza:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


In [19]:
#punto 3 
#Estrarre tre subarray di dimensione 2x2 dalle 
#prime due colonne (sub1, sub2, sub3)
sub1=es4[:2,:2]
print("sub1:\n", sub1)
sub2=es4[2:4,:2]
print("sub2:\n", sub2)
sub3=es4[4:,:2]
print("sub3:\n", sub3)

sub1:
 [[1 2]
 [7 8]]
sub2:
 [[13 14]
 [19 20]]
sub3:
 [[25 26]
 [31 32]]


In [36]:
#punto 4
#Concatenarli (usare concatenate) 
#prima usando axis=0 poi con axis=1
a=np.concatenate([sub1, sub2, sub3], axis=0)
print("concateno con axis=0:\n", a)
b=np.concatenate([sub1, sub2, sub3], axis=1)
print("concateno con axis=1:\n", b)

concateno con axis=0:
 [[ 1  2]
 [ 7  8]
 [13 14]
 [19 20]
 [25 26]
 [31 32]]
concateno con axis=1:
 [[ 1  2 13 14 25 26]
 [ 7  8 19 20 31 32]]


In [39]:
#punto5
#Da es4 estrarre un subarray formato dalle prime 
#due righe (sub4)
sub4=es4[:2,:]
print("sub4:\n", sub4)

sub4:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [45]:
#punto 6
#Concatenare sub1 a sub4. Usate hstack o vstack?
print("unisco sub1 e sub4:\n", np.hstack([sub1,sub4]))
#ho usato hstack perchè li ho uniti orizzontalmente

unisco sub1 e sub4:
 [[ 1  2  1  2  3  4  5  6]
 [ 7  8  7  8  9 10 11 12]]


In [75]:
#punto 7
#Trasformate sub4 da 2x6 a 6x2 
#(le 2 righe diventano 2 colonne)
sub4_trasformato=sub4.reshape(6,2)
print("sub4_trasformato:\n", sub4_trasformato)

sub4_trasformato:
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [55]:
#punto 8
#Concatenate sub1, sub2 e sub3 a formare un 
#nuovo array 6x2 (sub5)
sub5=np.concatenate([sub1, sub2, sub3])
print("sub5:\n", sub5)

sub5:
 [[ 1  2]
 [ 7  8]
 [13 14]
 [19 20]
 [25 26]
 [31 32]]


In [74]:
#punto 9
#Concatenate sub4 (trasformato) con sub5. hstack o vstack?
c=np.hstack([sub4_trasformato,sub5])
print("concateno orizzontalmente:\n", c)
d=np.vstack([sub4_trasformato,sub5])
print("concateno verticalmente:\n", d)
#posso concatenare sia orizzontalmente sia verticalmente
#in quanto i due subarray hanno lo stesso numero di righe
#e colonne

concateno orizzontalmente:
 [[ 1  2  1  2]
 [ 3  4  7  8]
 [ 5  6 13 14]
 [ 7  8 19 20]
 [ 9 10 25 26]
 [11 12 31 32]]
concateno verticalmente:
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [ 1  2]
 [ 7  8]
 [13 14]
 [19 20]
 [25 26]
 [31 32]]
