In [4]:
#Esercizio 2 08/10
#Creare un array es2a di valori casuali interi (randint) di dimensione 4x6, con valore massimo (incluso) uguale a 15
import numpy as np
es2a=np.random.randint(16, size=(4,6))
np.random.seed(0)
es2a

array([[ 8, 14,  5, 15,  2,  6],
       [11,  8,  9, 12,  1,  0],
       [ 5, 15,  6,  3,  3, 13],
       [ 8,  7,  1, 14, 13,  0]])

In [8]:
#selezionare le prime tre righe e le prime tre colonne
print("seleziono prime tre righe e prime tre colonne:\n",es2a[:3,:3])

seleziono prime tre righe e prime tre colonne:
 [[ 8 14  5]
 [11  8  9]
 [ 5 15  6]]


In [10]:
#selezionare seconda e terza riga e quarta quinta e sensta colonna
print("seconda e terza riga e quarta, quinta e sesta colonna:\n",es2a[1:3,3:])

seconda e terza riga e quarta, quinta e sesta colonna:
 [[12  1  0]
 [ 3  3 13]]


In [12]:
#selezionare elementi dopo il terzo elemento
print("elementi dopo il terzo elemento:\n",es2a[2,2:])

elementi dopo il terzo elemento:
 [ 6  3  3 13]


In [14]:
#invertire ordine sole righe e sole colonne
print("invertire ordine solo righe:\n",es2a[::-1])
print("invertire ordine solo colonne:\n",es2a[:,::-1])

invertire ordine solo righe:
 [[ 8  7  1 14 13  0]
 [ 5 15  6  3  3 13]
 [11  8  9 12  1  0]
 [ 8 14  5 15  2  6]]
invertire ordine solo colonne:
 [[ 6  2 15  5 14  8]
 [ 0  1 12  9  8 11]
 [13  3  3  6 15  5]
 [ 0 13 14  1  7  8]]


In [16]:
#Creare un array es2b di valori casuali interi (randint) di dimensione 5x5x2,con valore massimo (incluso) uguale a 30
import numpy as np
es2b= np.random.randint(31,size=(2,5,5))
np.random.seed(0)
es2b

array([[[12, 15, 21,  0,  3],
        [27,  3,  7,  9, 19],
        [21, 18,  4, 23,  6],
        [24, 24, 12, 26,  1],
        [ 6,  7, 23, 14, 24]],

       [[17,  5, 25, 13,  8],
        [ 9, 20, 19, 16, 19],
        [ 5, 30, 15, 15,  0],
        [18,  3, 24, 17, 19],
        [29, 19, 19, 14,  7]]])

In [18]:
#selezionare il primo subarray, da quello le prime 2 righe e le colonne dalla seconda alla quarta
print("primo subarray:\n",es2b[0,:2,1:4])


primo subarray:
 [[15 21  0]
 [ 3  7  9]]


In [19]:
#selezionare da entrambi i subarray le prime due righe e prime due colonne e invertire righe e colonne
print("due subarray:\n",es2b[:,:2,:2])
print("inverto righe e colonne:\n",es2b[:,::-1,::-1])

due subarray:
 [[[12 15]
  [27  3]]

 [[17  5]
  [ 9 20]]]
inverto righe e colonne:
 [[[24 14 23  7  6]
  [ 1 26 12 24 24]
  [ 6 23  4 18 21]
  [19  9  7  3 27]
  [ 3  0 21 15 12]]

 [[ 7 14 19 19 29]
  [19 17 24  3 18]
  [ 0 15 15 30  5]
  [19 16 19 20  9]
  [ 8 13 25  5 17]]]
