#### Esercizio 2 della lezione del 8/10/2020
Creare un array es1 di valori casuali interi (randint) di dimensione 3x5, con valore massimo (incluso) uguale a 8


In [42]:
import numpy as np
np.random.seed(0)
es1=np.random.randint(9,size=(3,5))
print("Matrice di partenza:\n",es1)
#Selezionare gli elementi che hanno valore 3 (uso 3 perché nel mio caso è il valore con più occorrenze in es1)
#prima utilizzando la posizione come indice
#poi usando la forma negativa dalla fine dell’array
print("\nSELEZIONO I VALORI UGUALI A TRE: ")
print("\nUso la la posizione come indice: ",es1[0,2],es1[0,3],es1[1,0])
print("\nUso a forma negativa dalla fine dell’array: ",es1[-3,-3], es1[-3,-2], es1[-2,-5])
#Selezionare:il primo elemento della seconda riga,il quinto elemento della prima riga,il secondo elemento della seconda colonna
#il quarto elemento della terza colonna
print("\nSELEZIONE ELEMENTI")
print("\nPrimo elemento della seconda riga: ",es1[1,0])
print("\nQuinto elemento della prima riga: ",es1[0,4])
print("\nSecondo elemento della seconda colonna: ",es1[1,1])
print("\nIl quarto elemento della terza colonna non esiste")
#Sommare 10 all’elemento es1[0,0],Sottrarre 5 all’elemento es1[2,2]
#Sommare l’elemento es1[0,0] all’elemento es1[1,0] e il risultato metterlo in es1[2,0]
print("\nSommare 10 all’elemento es1[0,0]: ",es1[0,0]+10)
print("\nSottrarre 5 all’elemento es1[3,2]: ",es1[2,2]-5)
es1[2,0]=es1[0,0]+es1[1,0]
print("\nSommare l’elemento es1[0,0] all’elemento es1[1,0] e il risultato metterlo in es1[2,0]:",es1[2,0])

Matrice di partenza:
 [[5 0 3 3 7]
 [3 5 2 4 7]
 [6 8 8 1 6]]

SELEZIONO I VALORI UGUALI A TRE: 

Uso la la posizione come indice:  3 3 3

Uso a forma negativa dalla fine dell’array:  3 3 3

SELEZIONE ELEMENTI

Primo elemento della seconda riga:  3

Quinto elemento della prima riga:  7

Secondo elemento della seconda colonna:  5

Il quarto elemento della terza colonna non esiste

Sommare 10 all’elemento es1[0,0]:  15

Sottrarre 5 all’elemento es1[3,2]:  3

Sommare l’elemento es1[0,0] all’elemento es1[1,0] e il risultato metterlo in es1[2,0]: 8
