In [10]:
import numpy as np
#Creare un array es3 di valori casuali interi (randint) di dimensione 3x3, con valore massimo (incluso) uguale a 20
es3= np.random.randint(21,size=(3,3))
print("la matrice originale è \n", es3)
#estrarre il subarray formato dalla seconda riga (es3_sub) come vista e visualizzarlo
sub1=es3[1,:]
print("\n Primo subarray: \n", sub1)
#moltiplicare per 3 tutti gli elementi della seconda colonna di es3
es3[:,1]=es3[:,1]*3
print("\n I valori moltiplicati della seconda colonna della matrice sono: ",es3[:,1])
#visualizzare es3_sub. È cambiato rispetto a prima?
print("\n Visualizzo il primo subarray dopo le modifiche: ",sub1)
#estrarre il subarray formato dalla terza colonna di es3 come copia (es3_sub_copy)
es3_sub_copy=es3[:,2].copy()
print("\n Copia del subarray della terza colonna: ", es3_sub_copy)
#sommare 10 a tutti gli elementi di es3_sub_copy e visualizzare
es3_sub_copy=es3_sub_copy+10
print("\n Modifiche alla copia del subarray: ", es3_sub_copy)
#visualizzare es3. Contiene la modifica del punto 6?
print("\n Visualizzo la matrice iniziale: \n", es3)


la matrice originale è 
 [[ 3  7 14]
 [10 10 18]
 [12 10 19]]

 Primo subarray: 
 [10 10 18]

 I valori moltiplicati della seconda colonna della matrice sono:  [21 30 30]

 Visualizzo il primo subarray dopo le modifiche:  [10 30 18]

 Copia del subarray della terza colonna:  [14 18 19]

 Modifiche alla copia del subarray:  [24 28 29]

 Visualizzo la matrice iniziale: 
 [[ 3 21 14]
 [10 30 18]
 [12 30 19]]


La matrice iniziale non contiene le modifiche fatte su es3_sub_copy in quanto il subarray era una copia