In [13]:
import numpy as np
# creare lista di 50 elementi
v1=np.zeros(50, dtype=int)
print("il vettore è: ",v1)
# creare matrice 2x5, di numeri interi
m1=np.ones((2, 5), dtype=float)
print("la matrice è: ", m1)
#creare matrice 3x3 con valori 12.34
m2=np.full((3, 3), 12.34)
print("la seconda matrice è: ", m2)
# creare lista di 10 elementi, che inizia da 6 e incrementa di 4 
l1=np.arange(6, 44, 4)
print("la lista è ",l1)
# creare lista di elementi tra 0 e 100 distanziati di 5 
l2=np.linspace(0, 100, 5)
print("la lista è: ",l2)
# creare matrice 1x10 di valori casuali tra 0 e 1
m3=np.random.random((1, 10))
print("la terza matrice è: ",m3)
# creare matrice 2x10 di valori con distribuzione gaussiana con media 0 e deviazione standard 1
m4=np.random.normal(0, 1, (2, 10))
print("la quarta matrice è: ",m4)


il vettore è:  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0]
la matrice è:  [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
la seconda matrice è:  [[12.34 12.34 12.34]
 [12.34 12.34 12.34]
 [12.34 12.34 12.34]]
la lista è  [ 6 10 14 18 22 26 30 34 38 42]
la lista è:  [  0.  25.  50.  75. 100.]
la terza matrice è:  [[0.65279032 0.63505887 0.99529957 0.58185033 0.41436859 0.4746975
  0.6235101  0.33800761 0.67475232 0.31720174]]
la quarta matrice è:  [[ 1.50944508  1.06777513 -0.68658948  0.01487332 -0.3756659  -0.03822364
   0.36797447 -0.0447237  -0.30237513 -2.2244036 ]
 [ 0.72400636  0.35900276  1.07612104  0.19214083  0.85292596  0.01835718
   0.42830357  0.99627783 -0.49114966  0.71267817]]
