#### Esercizio della lezione del 8/10/2020
Creare una lista es4 di 36 valori interi crescenti partendo da 1

In [32]:
import numpy as np

es4 = np.arange(1,37)
print("La lista di valori è: \n",es4)
#Trasformarlo in un array di dimensione 6x6
es4=es4.reshape(6,6)
print("\n Trasformazione della lista in una matrice: \n",es4)
#Estrarre tre subarray di dimensione 2x2 dalle prime due colonne (sub1, sub2, sub3)
sub1=es4[:2,:2]
print("\n PRIMO SUBARRAY:\n",sub1)
sub2=es4[:2,2:4]
print("\n SECONDO SUBARRAY:\n",sub2)
sub3=es4[:2,4:] 
print("\n TERZO SUBARRAY:\n",sub3)
#Concatenarli (usare concatenate) prima usando axis=0 poi con axis=1 
print("\n Concatenazione verticale subarray: \n",np.concatenate([sub1,sub2,sub3],axis=0))
print("\n Concatenazione orizzontale subarray: \n",np.concatenate([sub1,sub2,sub3],axis=1))
#Da es4 estrarre un subarray formato dalle prime due righe (sub4)
sub4=es4[:2,:]
print("\n QUARTO SUBARRAY:\n",sub4)
# Concatenare sub1 a sub4. Usate hstack o vstack?
print("\n Concatenazione del primo e del quarto subarray: \n",np.hstack([sub1,sub4]))
#Trasformate sub4 da 2x6 a 6x2 (le 2 righe diventano 2 colonne)
sub4=sub4.reshape(6,2)
print("\n Modifico il quarto subarry:\n",sub4)
#Concatenate sub1, sub2 e sub3 a formare un nuovo array 6x2 (sub5)
sub5=np.concatenate([sub1,sub2,sub3],axis=0)
print("\n QUINTO SUBARRAY:\n",sub5)
#Concatenate sub4 (trasformato) con sub5. hstack o vstack?
print("\n Concatenazione verticale del quarto e quinto subarray:\n",np.vstack([sub4,sub5]))
print("\n Concatenazione orizzontale quarto e quinto subarray:\n",np.hstack([sub4,sub5]))

La lista di valori è: 
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36]

 Trasformazione della lista in una matrice: 
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

 PRIMO SUBARRAY:
 [[1 2]
 [7 8]]

 SECONDO SUBARRAY:
 [[ 3  4]
 [ 9 10]]

 TERZO SUBARRAY:
 [[ 5  6]
 [11 12]]

 Concatenazione verticale subarray: 
 [[ 1  2]
 [ 7  8]
 [ 3  4]
 [ 9 10]
 [ 5  6]
 [11 12]]

 Concatenazione orizzontale subarray: 
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

 QUARTO SUBARRAY:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

 Concatenazione del primo e del quarto subarray: 
 [[ 1  2  1  2  3  4  5  6]
 [ 7  8  7  8  9 10 11 12]]

 Modifico il quarto subarry:
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]

 QUINTO SUBARRAY:
 [[ 1  2]
 [ 7  8]
 [ 3  4]
 [ 9 10]
 [ 5  6]
 [11 12]]

 Concatenazione verticale del quarto e quinto subarray:
 [[ 1  2]
 [ 