In [59]:
import numpy as np
np.random.seed(0) 
#Creare un array es1 di valori casuali interi (randint) di dimensione 3x5, con valore massimo (incluso) uguale a 8. 
#Visualizzare es1
es1 = np.random.randint(9, size=(3,5))  
print("MATRICE: \n" ,es1)
print("\n")
#selezionare gli elementi che hanno valore 5 (5 è un esempio, ovviamente potete scegliere un valore diverso), 
#prima utilizzando la posizione come indice, poi usando la forma negativa dalla fine dell’array (vedere esempi)
print("PRIMO NUMERO UGUALE A 5")
print("elemento con posizione come indice: " ,es1[0,0]) 
print("elemento con forma negativa: ", es1[0,-5])
print("SECONDO NUMERO UGUALE A 5")
print("elemento con posizione come indice: " ,es1[1,1]) 
print("elemento con forma negativa: ", es1[1,-4])
print(" \n")
#Selezionare il primo elemento della seconda riga, il quinto elemento della prima riga,
#il secondo elemento della seconda colonna e il quarto elemento della terza colonna
print("SELEZIONE ELEMENTI")
print("primo elemento della seconda riga: ", es1[1,0])
print("quinto elemento della prima riga: ", es1[0,4])
print("secondo elemento della seconda colonna: ", es1[1,1])
print("terzo elemento della terza colonna: ", es1[2,2])
print("\n")
#Sommare 10 all’elemento es1[0,0], sottrarre 5 all’elemento es1[3,2],
#sommare l’elemento es1[0,0] all’elemento es1[1,0] e il risultato metterlo in es1[2,0]
#(non usare i valori, usare i riferimenti alle posizioni dell’array)
es1[0,0] = es1[0,0]+10
es1[2,2] = es1[2,2]-5
es1[2,0]= es1[0,0]+es1[1,0]
print("NUOVA MATRICE: \n", es1)






MATRICE: 
 [[5 0 3 3 7]
 [3 5 2 4 7]
 [6 8 8 1 6]]


PRIMO NUMERO UGUALE A 5
elemento con posizione come indice:  5
elemento con forma negativa:  5
SECONDO NUMERO UGUALE A 5
elemento con posizione come indice:  5
elemento con forma negativa:  5
 

SELEZIONE ELEMENTI
primo elemento della seconda riga:  3
quinto elemento della prima riga:  7
secondo elemento della seconda colonna:  5
terzo elemento della terza colonna:  8


NUOVA MATRICE: 
 [[15  0  3  3  7]
 [ 3  5  2  4  7]
 [18  8  3  1  6]]
