In [1]:
import numpy as np

In [10]:
# creare array di 10 valori ma che parta da 5 fino a 15
es1= np.arange(5,15)
es1

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [33]:
#punto 1
print("primi sei valori:\n", es1[:6])

primi sei valori:
 [ 5  6  7  8  9 10]


In [18]:
#punto 2
print("elemento di indice 3:\n", es1[3])
print("elementi dopo l’indice 3:\n", es1[4:])

elemento di indice 3:
 8
elementi dopo l’indice 3:
 [ 9 10 11 12 13 14]


In [21]:
#punto 3
print("terzo elemento:\n", es1[2])
print("elementi dopo il terzo elemento:\n", es1[3:])

terzo elemento:
 7
elementi dopo il terzo elemento:
 [ 8  9 10 11 12 13 14]


In [34]:
#punto 4 (subarray con valori 8,9,10,11,12)
print("subarray:\n", es1[3:8])

subarray:
 [ 8  9 10 11 12]


In [35]:
#punto 5 
print("un elemento ogni tre, partendo dal primo:\n", es1[0::3])

un elemento ogni tre, partendo dal primo:
 [ 5  8 11 14]


In [36]:
#punto 6
print("un elemento ogni tre partendo dal terzo elemento:\n", es1[2::3])

un elemento ogni tre partendo dal terzo elemento:
 [ 7 10 13]
