In [1]:
import numpy as np

### PARTE 1 con array es2a

In [18]:
es2a=np.random.randint(16, size=(4,6))
np.random.seed(0)
es2a

array([[12, 15,  5,  0,  3, 11],
       [ 3,  7,  9,  3,  5,  2],
       [ 4,  7,  6,  8,  8, 12],
       [10,  1,  6,  7,  7, 14]])

In [51]:
#punto 1
print("prime tre righe, prime tre colonne:\n", es2a[:3,:3])

prime tre righe, prime tre colonne:
 [[12 15  5]
 [ 3  7  9]
 [ 4  7  6]]


In [24]:
#punto 2
print("seconda e terza riga, quarta, quinta e sesta colonna:\n", es2a[1:3,3:])

seconda e terza riga, quarta, quinta e sesta colonna:
 [[ 3  5  2]
 [ 8  8 12]]


In [27]:
#punto 3
print("elementi dopo il terzo elemento:\n", es2a[2,2:])

elementi dopo il terzo elemento:
 [ 6  8  8 12]


In [50]:
#punto 4
print("invertire l’ordine delle sole righe:\n", es2a[::-1])
print("invertire l'ordine delle sole colonne:\n", es2a[:, ::-1])
print("invertire sia righe sia colonne:\n", es2a[::-1, ::-1])


invertire l’ordine delle sole righe:
 [[10  1  6  7  7 14]
 [ 4  7  6  8  8 12]
 [ 3  7  9  3  5  2]
 [12 15  5  0  3 11]]
invertire l'ordine delle sole colonne:
 [[11  3  0  5 15 12]
 [ 2  5  3  9  7  3]
 [12  8  8  6  7  4]
 [14  7  7  6  1 10]]
invertire sia righe sia colonne:
 [[14  7  7  6  1 10]
 [12  8  8  6  7  4]
 [ 2  5  3  9  7  3]
 [11  3  0  5 15 12]]


### PARTE 2 con array es2b

In [69]:
import numpy as np
es2b= np.random.randint(31, size=(2,5,5))
np.random.seed(0)
es2b

array([[[12, 15, 21,  0,  3],
        [27,  3,  7,  9, 19],
        [21, 18,  4, 23,  6],
        [24, 24, 12, 26,  1],
        [ 6,  7, 23, 14, 24]],

       [[17,  5, 25, 13,  8],
        [ 9, 20, 19, 16, 19],
        [ 5, 30, 15, 15,  0],
        [18,  3, 24, 17, 19],
        [29, 19, 19, 14,  7]]])

In [72]:
#punto 1
#selezionare il primo subarray, 
#da quello le prime 2 righe e le colonne dalla seconda alla quarta
print("punto uno:\n", es2b[0,:2,1:4])

primo subarray modifocato:
 [[15 21  0]
 [ 3  7  9]]


In [81]:
#punto 2
#selezionare da entrambi i subarray le prime due righe e prime due 
#colonne e invertire righe e colonne
print("es2bprova:\n", es2b[:,:2,:2])
print("inverto righe e colonne:\n", es2bprova[:,::-1,::-1])

es2bprova:
 [[[12 15]
  [27  3]]

 [[17  5]
  [ 9 20]]]
inverto righe e colonne:
 [[[ 3 27]
  [15 12]]

 [[20  9]
  [ 5 17]]]
